//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWMetricas.Dominio.Mensagens
{
	using System;


	/// <summary>
	///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
	/// </summary>
	// Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
	// através de uma ferramenta como ResGen ou Visual Studio.
	// Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
	// com a opção /str, ou recrie o projeto do VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Mensagens
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Mensagens()
		{
		}

		/// <summary>
		///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWMetricas.Dominio.Mensagens.Mensagens", typeof(Mensagens).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Substitui a propriedade CurrentUICulture do thread atual para todas as
		///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Alteração realizada com sucesso..
		/// </summary>
		public static string AlteracaoSucesso
		{
			get
			{
				return ResourceManager.GetString("AlteracaoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Aprovação realizada com sucesso..
		/// </summary>
		public static string AprovacaoSucesso
		{
			get
			{
				return ResourceManager.GetString("AprovacaoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Ativação realizada com sucesso..
		/// </summary>
		public static string AtivoSucesso
		{
			get
			{
				return ResourceManager.GetString("AtivoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao atualizar vínculo de secretaria..
		/// </summary>
		public static string AtualizarVinculoErro
		{
			get
			{
				return ResourceManager.GetString("AtualizarVinculoErro", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Vínculo atualizado com sucesso..
		/// </summary>
		public static string AtualizarVinculoSucesso
		{
			get
			{
				return ResourceManager.GetString("AtualizarVinculoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Busca realizada com sucesso..
		/// </summary>
		public static string BuscaSucesso
		{
			get
			{
				return ResourceManager.GetString("BuscaSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro realizado com sucesso..
		/// </summary>
		public static string CadastroSucesso
		{
			get
			{
				return ResourceManager.GetString("CadastroSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a {0} não pode ser excluído, pois possui vínculos com {1}.
		/// </summary>
		public static string ExclusaoPossuiVinculo
		{
			get
			{
				return ResourceManager.GetString("ExclusaoPossuiVinculo", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Exclusão realizada com sucesso..
		/// </summary>
		public static string ExclusãoSucesso
		{
			get
			{
				return ResourceManager.GetString("ExclusãoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Erro de sincronia com Segurança..
		/// </summary>
		public static string FalhaAtualizacaoSegurancaBanco
		{
			get
			{
				return ResourceManager.GetString("FalhaAtualizacaoSegurancaBanco", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao buscar {0}..
		/// </summary>
		public static string FalhaBusca
		{
			get
			{
				return ResourceManager.GetString("FalhaBusca", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a {0} não pode ser excluído, pois possui vínculos com {1}..
		/// </summary>
		public static string FalhaExclusaoPossuiVinculo
		{
			get
			{
				return ResourceManager.GetString("FalhaExclusaoPossuiVinculo", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a {0} precisa estar vinculado ao menos a {1}..
		/// </summary>
		public static string FalhaPrecisaVinculo
		{
			get
			{
				return ResourceManager.GetString("FalhaPrecisaVinculo", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Inativação realizada com sucesso..
		/// </summary>
		public static string InativoSucesso
		{
			get
			{
				return ResourceManager.GetString("InativoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um {0} com o mesmo {1} cadastrado..
		/// </summary>
		public static string JaExiste
		{
			get
			{
				return ResourceManager.GetString("JaExiste", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Informe o campo {0} com até {1} caractér(es)..
		/// </summary>
		public static string MaxLength
		{
			get
			{
				return ResourceManager.GetString("MaxLength", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Informe o campo {0} com no mínimo {1} caractér(es)..
		/// </summary>
		public static string MinLength
		{
			get
			{
				return ResourceManager.GetString("MinLength", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrada..
		/// </summary>
		public static string NaoEncontrada
		{
			get
			{
				return ResourceManager.GetString("NaoEncontrada", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrado..
		/// </summary>
		public static string NaoEncontrado
		{
			get
			{
				return ResourceManager.GetString("NaoEncontrado", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Insira um número inteiro válido..
		/// </summary>
		public static string NumeroInteiroValido
		{
			get
			{
				return ResourceManager.GetString("NumeroInteiroValido", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Reprovação realizada com sucesso..
		/// </summary>
		public static string ReprovadoSucesso
		{
			get
			{
				return ResourceManager.GetString("ReprovadoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a O preenchimento do campo {0} é obrigatório..
		/// </summary>
		public static string Required
		{
			get
			{
				return ResourceManager.GetString("Required", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a O {0} não pode ter mais de {1} caractéres..
		/// </summary>
		public static string TamanhoMaximo
		{
			get
			{
				return ResourceManager.GetString("TamanhoMaximo", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a A {0} não pode ter mais de {1} caractéres..
		/// </summary>
		public static string TamanhoMaximo_a_
		{
			get
			{
				return ResourceManager.GetString("TamanhoMaximo(a)", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a O {0} não pode ter menos de {1} caractéres..
		/// </summary>
		public static string TamanhoMinimo
		{
			get
			{
				return ResourceManager.GetString("TamanhoMinimo", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a A {0} não pode ter menos de {1} caractéres..
		/// </summary>
		public static string TamanhoMinimo_a_
		{
			get
			{
				return ResourceManager.GetString("TamanhoMinimo(a)", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} não é uma url http, https ou ftp válida..
		/// </summary>
		public static string Url
		{
			get
			{
				return ResourceManager.GetString("Url", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Url inválida..
		/// </summary>
		public static string UrlIvalida
		{
			get
			{
				return ResourceManager.GetString("UrlIvalida", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não autorizado..
		/// </summary>
		public static string UsuarioNaoAutorizado
		{
			get
			{
				return ResourceManager.GetString("UsuarioNaoAutorizado", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a A {0} não pode ser vazia..
		/// </summary>
		public static string Vazia
		{
			get
			{
				return ResourceManager.GetString("Vazia", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a O {0} não pode ser vazio..
		/// </summary>
		public static string Vazio
		{
			get
			{
				return ResourceManager.GetString("Vazio", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao pesquisar vínculo..
		/// </summary>
		public static string VinculoErro
		{
			get
			{
				return ResourceManager.GetString("VinculoErro", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a Vínculo realizado com sucesso..
		/// </summary>
		public static string VinculoSucesso
		{
			get
			{
				return ResourceManager.GetString("VinculoSucesso", resourceCulture);
			}
		}

		/// <summary>
		///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve estar entre {1} e {2}..
		/// </summary>
		public static string Range
		{
			get
			{
				return ResourceManager.GetString("Range", resourceCulture);
			}
		}

		public static string CadastroConjuntoDadoSucesso
		{

			get
			{
				return ResourceManager.GetString("CadastroConjuntoDadoSucesso", resourceCulture);
			}
		}
	}
}
